---
title: "Take-home Exercise 2: Spatio-temporal Analysis of COVID-19 Vaccination Trends at the Sub-district Level, DKI Jakarta"
date: "20 February 2023"
date-modified: "r Sys.Date()"
execute: 
  eval: true
  echo: true
  warning: false
editor: visual
---

## 1.0 Overview

### 1.1 Background

Since late December 2019, an outbreak of a novel coronavirus disease (COVID-19; previously known as 2019-nCoV) was reported in Wuhan, China, which had subsequently affected 210 countries worldwide. In general, COVID-19 is an acute resolved disease but it can also be deadly, with a 2% case fatality rate.

The COVID-19 vaccination in Indonesia is an ongoing mass immunisation in response to the COVID-19 pandemic in Indonesia. On 13 January 2021, the program commenced when President Joko Widodo was vaccinated at the presidential palace. In terms of total doses given, Indonesia ranks third in Asia and fifth in the world.

According to wikipedia, as of 5 February 2023 at 18:00 WIB (UTC+7), 204,266,655 people had received the first dose of the vaccine and 175,131,893 people had been fully vaccinated; 69,597,474 of them had been inoculated with the booster or the third dose, while 1,585,164 had received the fourth dose. Jakarta has the highest percentage of population fully vaccinated with 103.46%, followed by Bali and Special Region of Yogyakarta with 85.45% and 83.02% respectively.

Despite its compactness, the cumulative vaccination rate are not evenly distributed within DKI Jakarta. The question is where are the sub-districts with relatively higher number of vaccination rate and how they changed over time.

### 1.2 Problem Statement

Exploratory Spatial Data Analysis (ESDA) hold tremendous potential to address complex problems facing society. In this study, we will apply appropriate **Local Indicators of Spatial Association (LISA)** and **Emerging Hot Spot Analysis (EHSA)** to undercover the spatio-temporal trends of COVID-19 vaccination in DKI Jakarta.

### 1.3 The Data

#### 1.3.1 Aspatial Data

For the purpose of this assignment, data from [Riwayat File Vaksinasi DKI Jakarta](https://riwayat-file-vaksinasi-dki-jakarta-jakartagis.hub.arcgis.com/) will be used. Daily vaccination data are provides. You are only required to download either the first day of the month or last day of the month of the study period.

#### 1.3.2 Spatial Data

For the purpose of this study, DKI Jakarta administration boundary 2019 will be used. The data set can be downloaded at Indonesia Geospatial portal, specifically at [this page](https://www.indonesia-geospasial.com/2020/04/download-shapefile-shp-batas-desa.html).

**Note:** - The national Projected Coordinates Systems of Indonesia is DGN95 / Indonesia TM-3 zone 54.1. - Exclude all the outer islands from the DKI Jakarta sf data frame, and - Retain the first nine fields in the DKI Jakarta sf data frame. The ninth field JUMLAH_PEN = Total Population.

### 1.4 The Task

The specific tasks of this take-home exercise are as follows:

##### [Choropleth Mapping and Analysis]{.underline}

-   Compute the monthly vaccination rate from July 2021 to June 2022 at sub-district (also known as kelurahan in Bahasa Indonesia) level,
-   Prepare the monthly vaccination rate maps by using appropriate tmap functions,
-   Describe the spatial patterns revealed by the choropleth maps (not more than 200 words).

##### [Local Gi\* Analysis]{.underline}

With reference to the vaccination rate maps prepared in ESDA: - Compute local Gi\* values of the monthly vaccination rate, - Display the Gi\* maps of the monthly vaccination rate. The maps should only display the significant (i.e. p-value \< 0.05). - With reference to the analysis results, draw statistical conclusions (not more than 250 words).

##### [Emerging Hot Spot Analysis (EHSA)]{.underline}

With reference to the local Gi\* values of the vaccination rate maps prepared in the previous section: - Perform Mann-Kendall Test by using the spatio-temporal local Gi\* values, - Select three sub-districts and describe the temporal trends revealed (not more than 250 words), and - Prepared a EHSA map of the Gi\* values of vaccination rate. The maps should only display the significant (i.e. p-value \< 0.05). - With reference to the EHSA map prepared, describe the spatial patterns revelaed. (not more than 250 words).
