project:
  type: website

website:
  title: "is415-gaa-michellefaith"
  navbar:
    left:
      - text: "Hand-on Exercise"
        menu:
          - text: "Hand-on Exercise"
            href: "week2/handon2.html"
      - text: "In-class Exercise"
        menu:
          - text: "In-Class Exercise 2"
            href: "week2/handon2.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

