project:
  type: website

website:
  title: "is415-gaa-michellefaith"
  navbar:
    left:
      - text: "Hand-on Exercise"
        menu:
          - text: "Hand-on Exercise"
            href: "In-class_Ex/In-class_ex02/In-class_Ex02.html"
      - text: "In-class Exercise"
        menu:
          - text: "In-Class Exercise 2"
            href: "In-class_Ex/In-class_ex02/In-class_Ex02.html"
          - text: "In-Class Exercise 3"
            href: "In-class_Ex/In-class_ex03/In-class_Ex03.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

