project:
  type: website

website:
  title: "is415-gaa-michellefaith"
  navbar:
    left:
    - text: "In-class Exercise"
      menu:
        - text: "In-class Exercise 2"
          href: "In-class_Ex/In-class_ex02/In-class_ex02.html"

    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

