---
title: "In-class_Ex04"
date: "30 Januaury 2023"
date-modified: "r Sys.Date()"
execute: 
  eval: true
  echo: true
  warning: false
editor: visual
---

# Getting Started

## Installing and loading packages

```{r}
pacman::p_load(maptools, sf, raster, spatstat, tmap)
```

## importing data

```{r}
childcare_sf <-
  st_read("data/child-care-services-geojson.geojson") %>%
  st_transform(crs = 3414)
```

```{r}
sg_sf <- st_read(dsn = "data", 
                 layer="CostalOutline")
```

```{r}
mpsz_sf <- st_read(dsn = "data", 
                layer = "MP14_SUBZONE_WEB_PL")
```

```{r}
tmap_mode('view')
tm_shape(childcare_sf)+
  tm_dots(alph=1,
          size=0.01)+
  tm_view (set.zoom.limits = c(11,14))
```

```{r}

```

```{r}
childcare <- as_Spatial(childcare_sf)
mpsz <- as_Spatial(mpsz_sf)
sg <- as_Spatial(sg_sf)
```

### generic format

```{r}
childcare_sp <- as(childcare, "SpatialPoints")
sg_sp <- as(sg, "SpatialPolygons")
```

### ppp format

```{r}
childcare_ppp <- as(childcare_sp, "ppp")
childcare_ppp
```

```{r}
plot(childcare_ppp)
```

```{r}
summary(childcare_ppp)
```
